index:
    path: /
    controller: App\Controller\ListController::products

products:
    path: /list/products
    controller: App\Controller\ListController::products

reservations:
    path: /list/reservations
    controller: App\Controller\ListController::reservations

createproduct:  
    controller: App\Controller\CreateController::createproduct
    path: /create/createproduct


editproduct:
    controller: App\Controller\EditController::editproduct
    path: /edit/editproduct/{id}

createreservation:  
    controller: App\Controller\CreateController::createreservation
    path: /create/createreservation


editreservation:
    controller: App\Controller\EditController::editreservation
    path: /edit/editreservation/{id}

deletereservation:
    controller: App\Controller\EditController::deletereservation
    path: /edit/deletereservation/{id}
    
